site_name: Ubyx Rulebook
site_url: https://YOUR_USER.github.io/Ubyx-Rulebook
docs_dir: rules          # MkDocs will read from rules/
theme:
  name: material         # clean, mobile‑friendly
  features:
    - navigation.tabs
    - navigation.sections
plugins:
  - search
  - awesome-pages        # auto‑build nav & drop numeric prefixes
  - redirects            # future‑proof if you rename pages
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - footnotes
